arresteddevops/ado-hugo

data/guests/dbraverman.yml, data/guests/ddigangi.yml, data/guests/jsheehan.yml, data/guests/lcreamer.yml, data/guests/llagestee.yml, data/guests/mstratton.yml, data/guests/nbrengle.yml, data/guests/pobrien.yml, data/guests/thess.yml
Please take a look and see if this works. I added some fields and in some cases I'm not sure if a field is optional, but I have no content for it.
=> Adding guests - eps 1 through 4

themes/ado/layouts/episode/single.html
=> Add social icons for guests.

themes/ado/layouts/episode/single.html, themes/ado/layouts/index.html, themes/ado/layouts/partials/header.html, themes/ado/static/css/style.css
=> moved social buttons around and cleaned up episode page

themes/ado/layouts/index.html
=> change subscribe to clean buttons.

themes/ado/layouts/partials/header.html, themes/ado/static/css/style.css
=> Make links for social buttons and clean up.

themes/ado/layouts/index.html, themes/ado/layouts/rss.xml
Added the new description to both the front page and the RSS feed (which will update iTunes and the like)
=> Add updated description

data/guests/mcurry.yml
=> Added Matt Curry's LinkedIn.

content/episode/git-101.md
Show notes added for git 101 episode.
=> adding got101 show notes

content/episode/speaking.md
=> fix markdown on speaking episode and add links

themes/ado/layouts/episode/single.html
=> Add some styling around the guests section

archetypes/episode.md, content/episode/availability.md, themes/ado/layouts/rss.xml
=> Add support for explicit tag

jerry.txt
fixes arresteddevops/ado-hugo#199
=> Make a fake file

content/episode/communities.md, content/episode/continuous-integration.md, content/episode/devops-mythbusters.md, content/episode/infrastructure-as-code.md, content/episode/tdi.md, content/episode/vendors.md, static/old_redirects
Got a bunch of broken links. This fixes it.
=> Fix ssl content

content/page/podcasts.md, layouts/shortcodes/podcast.html
=> add podcast shortcode and first podcast

content/episode/career-ops.md
=> Make tweets embedded on career ops

themes/ado/layouts/rss.xml
=> Change enclosure type and remove extra copyright

content/episode/open-source.md
Fixes https://github.com/arresteddevops/ado-hugo/issues/143
Fixes https://github.com/arresteddevops/ado-hugo/issues/145
=> Adding link to panel and correcting quote attr.

themes/ado/layouts/partials/head.html
This was making deploy previews all wonky
=> Remove base href tag.

content/page/podcasts.md
=> add some more podcasts

themes/ado/layouts/partials/header.html
=> Remove nav link to CFP's and website issues

data/hosts/bkromhout.yml
=> Bridget switched jobs

themes/ado/layouts/episode/single.html
this change will remove the comments from episode pages, in theory :)
=> Remove disqus from episode pages

data/hosts/thess.yml
Signed-off-by: Trevor Hess <trevor.ghess@gmail.com>
=> update Trevor host bio

.gitignore, netlify.toml, themes/ado/layouts/index.html, themes/ado/layouts/rss.xml, themes/ado/layouts/section/episode.rss.xml
- Update the links on the home page to point to the new feed
- Add episode images to the feed
- Add show notes to the feed
- Add GPM tags to the feed
=> Update podcast feed with all the fun stuff

data/guests/nharvey3.yml, static/img/guests/nharvey3.png
Signed-off-by: Nathen Harvey <nharvey@chef.io>
=> New bio for @nathenharvey

config.toml, content/host/matt.md, data/guests/mstratton.yml, data/guests/mstratton2.yml, data/guests/mstratton3.yml, data/hosts/mstratton.yml, static/humans.txt, themes/ado/layouts/index.html, themes/ado/layouts/rss.xml, themes/ado/layouts/section/episode.rss.xml, themes/ado/theme.toml
If you like ... 
Signed-off-by: Nathen Harvey <nharvey@chef.io>
=> Help us help you become 'Matty'

content/page/blogs.md, data/guests/mstratton3.yml, data/hosts/mstratton.yml, themes/ado/layouts/index.html
=> More Matty

content/page/books.md
=> Add some books

content/episode/certifications.md, content/episode/shiny-objects.md, content/episode/unreliable-things.md
These Velocity and devopsdays discount codes have been available for a bit now.
=> Adding missing discount codes

content/episode/unreliable-things.md
Accidentally kept previous ep release date
=> Fixing ep release date

content/episode/shiny-objects.md
=> Adding link to their new podcast

content/episode/the-meltwater-transformation.md
Forgot to set the time correctly
=> Bump ep to now

.devcontainer/devcontainer.json, .devcontainer/docker-compose.yml, .gitignore, README.md, docker-compose.yml
This alleviates the need for anyone to install or upgrade hugo
=> Hugo in docker

content/guest/jharper.md
Looks like a copy/paste error.
=> Fixing typo

themes/castanet/layouts/episode/single.html, themes/castanet/theme.toml
This is just a bugfix to make sure twitch icons show up on episode pages too :)
=> Updating theme to 1.3.1

content/guest/pcheslock.md, content/guest/pcheslock2.md, content/guest/pcheslock3.md
This also moves all three bios into "aka"
=> Update Pete Cheslock bio

themes/castanet/CHANGELOG.md, themes/castanet/REFERENCE.md, themes/castanet/archetypes/guest.md, themes/castanet/layouts/guest/list.html, themes/castanet/layouts/guest/single.html, themes/castanet/layouts/host/single.html, themes/castanet/layouts/partials/hosts.html, themes/castanet/theme.toml
this adds support for guest_group
=> Releasing theme version 1.4.0

config.toml, content/episode/chatting-with-pauly-comtois.md, content/search.md, layouts/_default/index.json, layouts/shortcodes/staticsearch.html, static/js/search.js
Searches guests and episodes!
Signed-off-by: Matt Stratton <matt.stratton@gmail.com>
=> Add search to the site

.github/workflows/calibreapp-webp-optimizer.yml, README.md
Update the image compression workflow slightly, and update README
=> Image workflow docs

config.toml
html in markdown pages was being weird with some stuff. this should fix it
=> Fix renderer HTML issue

content/episode/learning-to-learn.md, static/transcripts/learning-to-learn.md
Signed-off-by: Matt Stratton <matt.stratton@hey.com>
=> Add transcript for shelby episode

content/guest/mstratton4.md, content/host/mstratton.md
Signed-off-by: Matt Stratton <matt.stratton@hey.com>
=> Update matt’s twitch

content/host/mstratton.md
Note: this is embargoed until 29 March
=> Update Matt's bio

.github/workflows/calibreapp-webp-optimizer.yml
=> Fix image compression schedule
